ADDITIONAL_EXCLUDED_DIRECTORIES:
  - vendor
ENABLE_LINTERS:
  - ACTION_ZIZMOR
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - GO_GOLANGCI_LINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - YAML_YAMLLINT
REPOSITORY_KICS_ARGUMENTS: "--fail-on high"
