# SPDX-License-Identifier: Apache-2.0

FROM golang:1.26@sha256:32c0e6e5c4f6707717051091b4d0b077464a679eaab563e11474efc5328e2aa5 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG GOFIPS140=
RUN GOFIPS140=${GOFIPS140} CGO_ENABLED=0 go build -o /complytime-monitor ./cmd/monitor/

FROM gcr.io/distroless/static-debian12:nonroot@sha256:d093aa3e30dbadd3efe1310db061a14da60299baff8450a17fe0ccc514a16639

USER 65532

COPY --from=builder /complytime-monitor /complytime-monitor

# trivy:ignore:DS-0026 -- distroless has no shell or curl for HEALTHCHECK
ENTRYPOINT ["/complytime-monitor"]
