# SPDX-License-Identifier: Apache-2.0

FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG GOFIPS140=
RUN GOFIPS140=${GOFIPS140} CGO_ENABLED=0 go build -o /studio-witness ./cmd/witness/

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /studio-witness /studio-witness

ENTRYPOINT ["/studio-witness"]
