// Package gateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package gateway

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for JobStatusStatus.
const (
	Failed  JobStatusStatus = "failed"
	Pending JobStatusStatus = "pending"
	Sealed  JobStatusStatus = "sealed"
)

// Valid indicates whether the value is a known member of the JobStatusStatus enum.
func (e JobStatusStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Sealed:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// IngestResponse defines model for IngestResponse.
type IngestResponse struct {
	// JobId Unique identifier for the ingestion job
	JobId openapi_types.UUID `json:"jobId"`
}

// JobStatus defines model for JobStatus.
type JobStatus struct {
	// Digest Hex-encoded SHA-256 digest (only present if status is sealed)
	Digest *string `json:"digest,omitempty"`

	// JobId Job identifier
	JobId openapi_types.UUID `json:"jobId"`

	// LogIndex Log index (only present if status is sealed)
	LogIndex *int64 `json:"logIndex,omitempty"`

	// Status Current job status
	Status JobStatusStatus `json:"status"`
}

// JobStatusStatus Current job status
type JobStatusStatus string

// SubjectRegistrationRequest defines model for SubjectRegistrationRequest.
type SubjectRegistrationRequest struct {
	// SubjectId Unique identifier for the subject
	SubjectId string `json:"subjectId"`

	// TrustedPublishers List of trusted OIDC publishers for this subject
	TrustedPublishers []TrustedPublisher `json:"trustedPublishers"`
}

// SubjectRegistrationResponse defines model for SubjectRegistrationResponse.
type SubjectRegistrationResponse struct {
	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`
}

// TrustedPublisher defines model for TrustedPublisher.
type TrustedPublisher struct {
	// Issuer OIDC issuer URL
	Issuer string `json:"issuer"`

	// Sub OIDC subject claim pattern
	Sub string `json:"sub"`
}

// IngestArtifactJSONBody defines parameters for IngestArtifact.
type IngestArtifactJSONBody = map[string]interface{}

// IngestArtifactApplicationVndDssePlusJSONBody defines parameters for IngestArtifact.
type IngestArtifactApplicationVndDssePlusJSONBody = map[string]interface{}

// RegisterSubjectJSONRequestBody defines body for RegisterSubject for application/json ContentType.
type RegisterSubjectJSONRequestBody = SubjectRegistrationRequest

// IngestArtifactJSONRequestBody defines body for IngestArtifact for application/json ContentType.
type IngestArtifactJSONRequestBody = IngestArtifactJSONBody

// IngestArtifactApplicationVndDssePlusJSONRequestBody defines body for IngestArtifact for application/vnd.dsse+json ContentType.
type IngestArtifactApplicationVndDssePlusJSONRequestBody = IngestArtifactApplicationVndDssePlusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register subject with trusted publishers
	// (POST /api/admin/subjects)
	RegisterSubject(w http.ResponseWriter, r *http.Request)
	// Submit artifact for ingestion
	// (POST /api/ingest)
	IngestArtifact(w http.ResponseWriter, r *http.Request)
	// Poll job status
	// (GET /api/ingest/jobs/{jobId})
	GetJobStatus(w http.ResponseWriter, r *http.Request, jobId openapi_types.UUID)
	// Health check endpoint
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register subject with trusted publishers
// (POST /api/admin/subjects)
func (_ Unimplemented) RegisterSubject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit artifact for ingestion
// (POST /api/ingest)
func (_ Unimplemented) IngestArtifact(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Poll job status
// (GET /api/ingest/jobs/{jobId})
func (_ Unimplemented) GetJobStatus(w http.ResponseWriter, r *http.Request, jobId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RegisterSubject operation middleware
func (siw *ServerInterfaceWrapper) RegisterSubject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterSubject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestArtifact operation middleware
func (siw *ServerInterfaceWrapper) IngestArtifact(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestArtifact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJobStatus operation middleware
func (siw *ServerInterfaceWrapper) GetJobStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "jobId" -------------
	var jobId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "jobId", chi.URLParam(r, "jobId"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJobStatus(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/admin/subjects", wrapper.RegisterSubject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/ingest", wrapper.IngestArtifact)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/ingest/jobs/{jobId}", wrapper.GetJobStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})

	return r
}
