// Package gateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package gateway

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// IngestResponse defines model for IngestResponse.
type IngestResponse struct {
	// JobId Unique identifier for the ingestion job
	JobId openapi_types.UUID `json:"jobId"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// ArtifactType Type of artifact that failed validation
	ArtifactType string `json:"artifactType"`

	// Details Field-level validation errors
	Details []string `json:"details"`

	// Error Error message
	Error string `json:"error"`
}

// IngestArtifactJSONBody defines parameters for IngestArtifact.
type IngestArtifactJSONBody = map[string]interface{}

// IngestArtifactApplicationVndDssePlusJSONBody defines parameters for IngestArtifact.
type IngestArtifactApplicationVndDssePlusJSONBody = map[string]interface{}

// IngestArtifactParams defines parameters for IngestArtifact.
type IngestArtifactParams struct {
	// XSubjectID Subject identifier for the artifact
	XSubjectID string `json:"X-Subject-ID"`
}

// IngestArtifactJSONRequestBody defines body for IngestArtifact for application/json ContentType.
type IngestArtifactJSONRequestBody = IngestArtifactJSONBody

// IngestArtifactApplicationVndDssePlusJSONRequestBody defines body for IngestArtifact for application/vnd.dsse+json ContentType.
type IngestArtifactApplicationVndDssePlusJSONRequestBody = IngestArtifactApplicationVndDssePlusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit artifact for ingestion
	// (POST /api/ingest)
	IngestArtifact(w http.ResponseWriter, r *http.Request, params IngestArtifactParams)
	// Health check endpoint
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Submit artifact for ingestion
// (POST /api/ingest)
func (_ Unimplemented) IngestArtifact(w http.ResponseWriter, r *http.Request, params IngestArtifactParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// IngestArtifact operation middleware
func (siw *ServerInterfaceWrapper) IngestArtifact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IngestArtifactParams

	headers := r.Header

	// ------------- Required header parameter "X-Subject-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Subject-ID")]; found {
		var XSubjectID string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Subject-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Subject-ID", valueList[0], &XSubjectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Subject-ID", Err: err})
			return
		}

		params.XSubjectID = XSubjectID

	} else {
		err := fmt.Errorf("Header parameter X-Subject-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Subject-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestArtifact(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/ingest", wrapper.IngestArtifact)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})

	return r
}
