// Package graph provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package graph

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CoverageControlStatus.
const (
	Covered   CoverageControlStatus = "covered"
	Uncovered CoverageControlStatus = "uncovered"
)

// Valid indicates whether the value is a known member of the CoverageControlStatus enum.
func (e CoverageControlStatus) Valid() bool {
	switch e {
	case Covered:
		return true
	case Uncovered:
		return true
	default:
		return false
	}
}

// ArtifactTypeSummary defines model for ArtifactTypeSummary.
type ArtifactTypeSummary struct {
	// Count Number of artifacts of this type
	Count int64 `json:"count"`

	// LastUpdated Timestamp of most recent artifact
	LastUpdated time.Time `json:"lastUpdated"`
}

// CoverageControl defines model for CoverageControl.
type CoverageControl struct {
	// Id Control identifier
	Id string `json:"id"`

	// LatestEvidence Timestamp of latest evidence for this control
	LatestEvidence *time.Time `json:"latestEvidence,omitempty"`

	// Status Coverage status
	Status CoverageControlStatus `json:"status"`

	// Title Control title
	Title string `json:"title"`
}

// CoverageControlStatus Coverage status
type CoverageControlStatus string

// CoverageResponse defines model for CoverageResponse.
type CoverageResponse struct {
	// Catalog Catalog identifier
	Catalog string `json:"catalog"`

	// CatalogType Type of catalog
	CatalogType string `json:"catalogType"`

	// Controls Coverage details per control
	Controls []CoverageControl `json:"controls"`

	// Covered Number of covered controls
	Covered int `json:"covered"`

	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`

	// Total Total number of controls
	Total int `json:"total"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// EvidenceItem defines model for EvidenceItem.
type EvidenceItem struct {
	// ArtifactType Type of artifact
	ArtifactType string `json:"artifactType"`

	// Digest Receipt digest
	Digest string `json:"digest"`

	// LogIndex Transparency log index
	LogIndex  int64             `json:"logIndex"`
	Publisher PublisherIdentity `json:"publisher"`

	// Sealed Seal timestamp
	Sealed time.Time `json:"sealed"`

	// Status Processing status
	Status string `json:"status"`
}

// EvidenceListResponse defines model for EvidenceListResponse.
type EvidenceListResponse struct {
	// Evidence Evidence items
	Evidence []EvidenceItem `json:"evidence"`

	// NextCursor Pagination cursor for next page
	NextCursor *string `json:"nextCursor,omitempty"`

	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`
}

// EvidenceSource defines model for EvidenceSource.
type EvidenceSource struct {
	// Digest Receipt digest
	Digest string `json:"digest"`

	// LogIndex Transparency log index
	LogIndex  int64             `json:"logIndex"`
	Publisher PublisherIdentity `json:"publisher"`

	// Sealed Seal timestamp
	Sealed time.Time `json:"sealed"`
}

// PublisherIdentity defines model for PublisherIdentity.
type PublisherIdentity struct {
	// Issuer OIDC issuer URL
	Issuer string `json:"issuer"`

	// Sub OIDC subject claim
	Sub string `json:"sub"`
}

// SubjectDetail defines model for SubjectDetail.
type SubjectDetail struct {
	// ArtifactTypes Map of artifact type to summary with freshness
	ArtifactTypes map[string]ArtifactTypeSummary `json:"artifactTypes"`

	// EvidenceCount Total evidence count
	EvidenceCount int64 `json:"evidenceCount"`

	// Id Subject identifier
	Id string `json:"id"`

	// PublisherCount Number of unique publishers
	PublisherCount int `json:"publisherCount"`
}

// SubjectSummary defines model for SubjectSummary.
type SubjectSummary struct {
	// ArtifactTypes Map of artifact type to summary
	ArtifactTypes map[string]ArtifactTypeSummary `json:"artifactTypes"`

	// EvidenceCount Total evidence count
	EvidenceCount int64 `json:"evidenceCount"`

	// Id Subject identifier
	Id string `json:"id"`

	// PublisherCount Number of unique publishers
	PublisherCount int `json:"publisherCount"`
}

// ThreatModelCapability defines model for ThreatModelCapability.
type ThreatModelCapability struct {
	// Description Capability description
	Description string `json:"description"`

	// Id Capability identifier
	Id string `json:"id"`

	// Introduces IDs of threats this capability introduces
	Introduces []string       `json:"introduces"`
	Source     EvidenceSource `json:"source"`

	// Title Capability title
	Title string `json:"title"`
}

// ThreatModelControl defines model for ThreatModelControl.
type ThreatModelControl struct {
	// Applies IDs of threats this control applies to
	Applies []string `json:"applies"`

	// AssessmentRequirements Assessment requirement descriptions
	AssessmentRequirements []string `json:"assessmentRequirements"`

	// Id Control identifier
	Id string `json:"id"`

	// Objective Control objective
	Objective string         `json:"objective"`
	Source    EvidenceSource `json:"source"`

	// Title Control title
	Title string `json:"title"`
}

// ThreatModelResponse defines model for ThreatModelResponse.
type ThreatModelResponse struct {
	// Capabilities System capabilities
	Capabilities []ThreatModelCapability `json:"capabilities"`

	// Controls Security controls
	Controls []ThreatModelControl `json:"controls"`

	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`

	// Threats Identified threats
	Threats []ThreatModelThreat `json:"threats"`

	// Vectors Attack vectors
	Vectors []ThreatModelVector `json:"vectors"`
}

// ThreatModelThreat defines model for ThreatModelThreat.
type ThreatModelThreat struct {
	// AddressedBy IDs of controls addressing this threat
	AddressedBy []string `json:"addressedBy"`

	// Description Threat description
	Description string `json:"description"`

	// Id Threat identifier
	Id string `json:"id"`

	// Leverages IDs of capabilities this threat leverages
	Leverages []string       `json:"leverages"`
	Source    EvidenceSource `json:"source"`

	// Title Threat title
	Title string `json:"title"`
}

// ThreatModelVector defines model for ThreatModelVector.
type ThreatModelVector struct {
	// Description Vector description
	Description string `json:"description"`

	// Id Vector identifier
	Id string `json:"id"`

	// Title Vector title
	Title string `json:"title"`
}

// GetCoverageParams defines parameters for GetCoverage.
type GetCoverageParams struct {
	// Catalog Catalog identifier (e.g., gemara:///com.example/catalog@1.0.0)
	Catalog string `form:"catalog" json:"catalog"`
}

// GetEvidenceParams defines parameters for GetEvidence.
type GetEvidenceParams struct {
	// Type Filter by artifact type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Since Filter evidence created after this timestamp
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Before Filter evidence created before this timestamp
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// Cursor Pagination cursor
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of results per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List subjects with summary statistics
	// (GET /api/subjects)
	ListSubjects(w http.ResponseWriter, r *http.Request)
	// Get subject detail with per-artifact-type freshness
	// (GET /api/subjects/{id})
	GetSubject(w http.ResponseWriter, r *http.Request, id string)
	// Get coverage report for a catalog
	// (GET /api/subjects/{id}/coverage)
	GetCoverage(w http.ResponseWriter, r *http.Request, id string, params GetCoverageParams)
	// Get paginated evidence list
	// (GET /api/subjects/{id}/evidence)
	GetEvidence(w http.ResponseWriter, r *http.Request, id string, params GetEvidenceParams)
	// Get assembled threat model (flat with provenance)
	// (GET /api/subjects/{id}/threat-model)
	GetThreatModel(w http.ResponseWriter, r *http.Request, id string)
	// Health check endpoint
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List subjects with summary statistics
// (GET /api/subjects)
func (_ Unimplemented) ListSubjects(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get subject detail with per-artifact-type freshness
// (GET /api/subjects/{id})
func (_ Unimplemented) GetSubject(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get coverage report for a catalog
// (GET /api/subjects/{id}/coverage)
func (_ Unimplemented) GetCoverage(w http.ResponseWriter, r *http.Request, id string, params GetCoverageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get paginated evidence list
// (GET /api/subjects/{id}/evidence)
func (_ Unimplemented) GetEvidence(w http.ResponseWriter, r *http.Request, id string, params GetEvidenceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get assembled threat model (flat with provenance)
// (GET /api/subjects/{id}/threat-model)
func (_ Unimplemented) GetThreatModel(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSubjects operation middleware
func (siw *ServerInterfaceWrapper) ListSubjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubject operation middleware
func (siw *ServerInterfaceWrapper) GetSubject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCoverage operation middleware
func (siw *ServerInterfaceWrapper) GetCoverage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCoverageParams

	// ------------- Required query parameter "catalog" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "catalog", r.URL.Query(), &params.Catalog, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "catalog"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "catalog", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoverage(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvidence operation middleware
func (siw *ServerInterfaceWrapper) GetEvidence(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEvidenceParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvidence(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetThreatModel operation middleware
func (siw *ServerInterfaceWrapper) GetThreatModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetThreatModel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/subjects", wrapper.ListSubjects)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/subjects/{id}", wrapper.GetSubject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/subjects/{id}/coverage", wrapper.GetCoverage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/subjects/{id}/evidence", wrapper.GetEvidence)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/subjects/{id}/threat-model", wrapper.GetThreatModel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})

	return r
}
