// Package locker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package locker

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// CreateLedgerRequest defines model for CreateLedgerRequest.
type CreateLedgerRequest struct {
	// SubjectId Unique identifier for the subject
	SubjectId string `json:"subjectId"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// LedgerInfo defines model for LedgerInfo.
type LedgerInfo struct {
	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`

	// VerifierKey Public verification key for checkpoint signatures
	VerifierKey string `json:"verifierKey"`
}

// LedgerList defines model for LedgerList.
type LedgerList struct {
	Ledgers []LedgerInfo `json:"ledgers"`
}

// ModifyTrustRequest defines model for ModifyTrustRequest.
type ModifyTrustRequest struct {
	// TrustedPublishers List of trusted OIDC publishers for this subject
	TrustedPublishers []TrustedPublisher `json:"trustedPublishers"`
}

// ModifyTrustResponse defines model for ModifyTrustResponse.
type ModifyTrustResponse struct {
	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`
}

// SealResponse defines model for SealResponse.
type SealResponse struct {
	// Digest Hex-encoded SHA-256 digest of the receipt
	Digest string `json:"digest"`

	// Index Log index assigned to the sealed receipt
	Index int64 `json:"index"`
}

// SubjectRegistrationRequest defines model for SubjectRegistrationRequest.
type SubjectRegistrationRequest struct {
	// SubjectId Unique identifier for the subject
	SubjectId string `json:"subjectId"`

	// TrustedPublishers List of trusted OIDC publishers for this subject
	TrustedPublishers []TrustedPublisher `json:"trustedPublishers"`
}

// SubjectRegistrationResponse defines model for SubjectRegistrationResponse.
type SubjectRegistrationResponse struct {
	// SubjectId Subject identifier
	SubjectId string `json:"subjectId"`
}

// TrustedPublisher defines model for TrustedPublisher.
type TrustedPublisher struct {
	// Issuer OIDC issuer URL
	Issuer string `json:"issuer"`

	// Sub OIDC subject claim pattern
	Sub string `json:"sub"`
}

// VerifyResponse defines model for VerifyResponse.
type VerifyResponse struct {
	// Found Whether the digest was found in the ledger
	Found bool `json:"found"`

	// Index Log index if found
	Index *int64 `json:"index,omitempty"`
}

// RegisterSubjectJSONRequestBody defines body for RegisterSubject for application/json ContentType.
type RegisterSubjectJSONRequestBody = SubjectRegistrationRequest

// ModifyTrustJSONRequestBody defines body for ModifyTrust for application/json ContentType.
type ModifyTrustJSONRequestBody = ModifyTrustRequest

// CreateLedgerJSONRequestBody defines body for CreateLedger for application/json ContentType.
type CreateLedgerJSONRequestBody = CreateLedgerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register subject with trusted publishers
	// (POST /admin/subjects)
	RegisterSubject(w http.ResponseWriter, r *http.Request)
	// Update trusted publishers for a subject
	// (PUT /admin/subjects/{subjectId}/trust)
	ModifyTrust(w http.ResponseWriter, r *http.Request, subjectId string)
	// Health check endpoint
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// List all ledgers
	// (GET /ledgers)
	ListLedgers(w http.ResponseWriter, r *http.Request)
	// Create a new ledger
	// (POST /ledgers)
	CreateLedger(w http.ResponseWriter, r *http.Request)
	// Get ledger information
	// (GET /ledgers/{subjectId})
	GetLedger(w http.ResponseWriter, r *http.Request, subjectId string)
	// Fetch a sealed receipt by index
	// (GET /ledgers/{subjectId}/entry/{index})
	FetchReceipt(w http.ResponseWriter, r *http.Request, subjectId string, index int64)
	// Seal a receipt in the ledger
	// (POST /ledgers/{subjectId}/seal)
	SealReceipt(w http.ResponseWriter, r *http.Request, subjectId string)
	// Verify a receipt exists by digest
	// (GET /ledgers/{subjectId}/verify/{digest})
	VerifyReceipt(w http.ResponseWriter, r *http.Request, subjectId string, digest string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register subject with trusted publishers
// (POST /admin/subjects)
func (_ Unimplemented) RegisterSubject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update trusted publishers for a subject
// (PUT /admin/subjects/{subjectId}/trust)
func (_ Unimplemented) ModifyTrust(w http.ResponseWriter, r *http.Request, subjectId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all ledgers
// (GET /ledgers)
func (_ Unimplemented) ListLedgers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new ledger
// (POST /ledgers)
func (_ Unimplemented) CreateLedger(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ledger information
// (GET /ledgers/{subjectId})
func (_ Unimplemented) GetLedger(w http.ResponseWriter, r *http.Request, subjectId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a sealed receipt by index
// (GET /ledgers/{subjectId}/entry/{index})
func (_ Unimplemented) FetchReceipt(w http.ResponseWriter, r *http.Request, subjectId string, index int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Seal a receipt in the ledger
// (POST /ledgers/{subjectId}/seal)
func (_ Unimplemented) SealReceipt(w http.ResponseWriter, r *http.Request, subjectId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify a receipt exists by digest
// (GET /ledgers/{subjectId}/verify/{digest})
func (_ Unimplemented) VerifyReceipt(w http.ResponseWriter, r *http.Request, subjectId string, digest string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RegisterSubject operation middleware
func (siw *ServerInterfaceWrapper) RegisterSubject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterSubject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ModifyTrust operation middleware
func (siw *ServerInterfaceWrapper) ModifyTrust(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "subjectId" -------------
	var subjectId string

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ModifyTrust(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLedgers operation middleware
func (siw *ServerInterfaceWrapper) ListLedgers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLedgers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLedger operation middleware
func (siw *ServerInterfaceWrapper) CreateLedger(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLedger(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLedger operation middleware
func (siw *ServerInterfaceWrapper) GetLedger(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "subjectId" -------------
	var subjectId string

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLedger(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FetchReceipt operation middleware
func (siw *ServerInterfaceWrapper) FetchReceipt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "subjectId" -------------
	var subjectId string

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index int64

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FetchReceipt(w, r, subjectId, index)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SealReceipt operation middleware
func (siw *ServerInterfaceWrapper) SealReceipt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "subjectId" -------------
	var subjectId string

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SealReceipt(w, r, subjectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyReceipt operation middleware
func (siw *ServerInterfaceWrapper) VerifyReceipt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "subjectId" -------------
	var subjectId string

	err = runtime.BindStyledParameterWithOptions("simple", "subjectId", chi.URLParam(r, "subjectId"), &subjectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subjectId", Err: err})
		return
	}

	// ------------- Path parameter "digest" -------------
	var digest string

	err = runtime.BindStyledParameterWithOptions("simple", "digest", chi.URLParam(r, "digest"), &digest, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "digest", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyReceipt(w, r, subjectId, digest)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/subjects", wrapper.RegisterSubject)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/subjects/{subjectId}/trust", wrapper.ModifyTrust)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ledgers", wrapper.ListLedgers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ledgers", wrapper.CreateLedger)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ledgers/{subjectId}", wrapper.GetLedger)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ledgers/{subjectId}/entry/{index}", wrapper.FetchReceipt)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ledgers/{subjectId}/seal", wrapper.SealReceipt)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ledgers/{subjectId}/verify/{digest}", wrapper.VerifyReceipt)
	})

	return r
}
